config/routes.rb
Rails.application.routes.draw do
  root :to => "apps#index"

  get '/apps/about' => 'apps#about', as: 'app_about'

  get '/apps/message' => 'apps#message', as: 'app_message'
  get '/apps/team' => 'apps#team', as: 'app_team'
  get '/apps/schedule' => 'apps#schedule', as: 'app_schedule'
  get '/apps/game' => 'apps#game', as: 'app_game'
  get '/apps/profile' => 'apps#profile', as: 'app_profile'

  get '/schedules/manage' => 'schedules#manage', as: 'schedules_manage'
  get '/team/manage/:id' => 'teams#manage', as: 'team_manage'

  get 'team/apply2team' => 'team_users#apply', as: 'apply_to_team'
  get 'team/invite2team' => 'team_users#invite', as: 'invite_to_team'

  # resources :users, only: [:show]
  resources :apps
  resources :teams
  resources :schedules
  resources :team_users
  resources :games

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team

	geocoded_by :place
	after_validation :geocode, :if => :place_changed?
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :team


	geocoded_by :place

end

app/models/schedule_user.rb
class ScheduleUser < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :team_users
	has_many :users, through: :team_users

	has_many :schedules
	attachment :image
	#mount_uploader :picture, PictureUploader
	geocoded_by :active_place
	after_validation :geocode, :if => :active_place_changed?

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Team.where(['team_key LIKE ?', "%#{search}%"])
      # Team.where(:team_key, "%#{search}%"])
    # else
	 # Team.all #全て表示。
    end
  end
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :team_users
	has_many :teams, through: :team_users
	accepts_nested_attributes_for :team_users


  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      User.where(['id LIKE ?', "%#{search}%"])
    else
      User.all #全て表示。
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
		# いずれかのチームの管理者か否か判定
		if user_signed_in?
			@admin = 0

			@admin = TeamUser.where("(user_id = ?) AND (admin = ?)", current_user.id,1)
			if @admin.presence
				@admin = true
			else
				@admin = false
			end

			@schedules = []
		 	teams = TeamUser.where(user_id: current_user.id).pluck(:team_id).uniq
			teams.each { |team|
	        schedule = nil
			  	# debugger
			  	schedule = []
			  	schedule << Team.where(id: team).pluck(:name)[0] # team name
			  	schedule << Schedule.where(team_id: team).pluck(:team_id, :name, :place)
				#参加人数
			  	#欠席人数
			  	#保留人数
			  	#debugger

	        @schedules << schedule
			# debugger
			}
		end
	end

	def message
	end
	
	def team
	end

	def schduele
	end

	def profile
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  	@game = Game.new
  end

  def create
  	@game = Game.new(game_params)
  	@game.team_id = 1
  	# debugger
  	@game.save
  	redirect_to new_game_path
  end


  private
    def game_params
    	params.require(:game).permit(:title, :place)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def manage
    @teamusers = TeamUser.where(user_id: current_user.id)
    # debugger

    @teams = []
    teams = TeamUser.where(user_id: current_user.id).pluck(:team_id).uniq
    teams.each { |team|
        schedule = nil
        schedule = Schedule.where(team_id: team).pluck(:name, :place, team.name)
        @schedules << schedule
    }

  end

  def new
  	@schedule = Schedule.new
    @admin_teams = TeamUser.where(user_id: current_user, admin: true)
    @admin_teams.count
    if @admin_teams.count >= 2
      @admin_team_flag = true
    else
      @admin_team_flag = false
    end
  end

  def create
  	@schedule = Schedule.new(schedule_params)
  	# @schedule.team_id = params[:team_id]

  	@schedule.save
    # debugger
  	redirect_to root_path
  end

  def index
		@schedules = []
	 	teams = TeamUser.where(user_id: current_user.id).pluck(:team_id).uniq
		teams.each { |team|
        schedule = nil
		  	schedule = Schedule.where(team_id: team).pluck(:name, :place, team.name)
        @schedules << schedule
		}
  end

  private
    def schedule_params
    	params.require(:schedule).permit(:name, :place, :team_id, :datetime, :remark)
    end
end

app/controllers/team_users_controller.rb
class TeamUsersController < ApplicationController
  def index
    # debugger
  	@team_users = TeamUser.where(user_id: current_user.id, admin: true)
  end
  
  def new
  	@team_user = TeamUser.new
    @team_id = params[:team_id]
    status = params[:status]
    # debugger
  end

  def create
    @team = TeamUser.new
    @team.team_id = params[:team_id]
    @team.user_id = current_user.id
    @team.admin = 0
    @team.status = params[:status]
    @team.save
    redirect_to root_path
  end

  def apply
    @teams = Team.search(params[:search])
  end

  def invite
      @teams = Team.search(params[:search])
  end

  private
  def team_params
  	params.require(:team_user).permit(:team_id, :user_id, :remark)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index

    @teams = current_user.teams.pluck(:id, :name, :image_id)
    @teams_info = []
    @teams.each{|team|
      team << TeamUser.where(team_id: team[0]).count
      @teams_info << team
    }

    @teams = Team.all
  end

  def invite
    @team_id = params[:team_id]
    debugger

    @users = User.search(params[:search])
    debugger
  end

  def join_new
  end

  def show
    @team = Team.find(params[:id])
    @team_menber = TeamUser.where(team_id: params[:id])

    @users = User.search(params[:search])
  end

  def new
  	@team = current_user.teams.build
  end

  def create
  	@team = current_user.teams.build(team_params)
    @team.active = true
    @team.team_key = SecureRandom.hex(5)

  	if @team.save
	  	@team_user = TeamUser.new
	  	@team_user.team_id = @team.id
	  	@team_user.user_id = current_user.id
	  	@team_user.status = 2
	  	@team_user.admin = 1
	  	if !(@team_user.save)
	  		@team.destroy
	  		redirect_to new_team_path , notice: "チームを作成できませんでした。"
	  	end
      # debugger
  		redirect_to team_path(@team), notice: "チームを作成しました。"
  	else
        redirect_to new_team_path , notice: "チームを作成できませんでした。"
  	end
  end

  def edit
    @team = Team.find(params[:id])

  end

  def update
    team = Team.find(params[:id])
    team.update(team_params)
    redirect_to team_path(team.id)

  end


  def manage
    
  end


  private
  def team_params
  	params.require(:team).permit(:name, :organization, :level, :active_place,:description, :team_key, :active, :image, :picture, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #ViewのFormで取得したパラメータをモデルに渡す
    # @users = User.search(params[:search])
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/team_user_helper.rb
module TeamUserHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="text-center">
						<span style="font-size:24px;">ゲームを登録</span>
					</div>
					<hr>
				</div>
				<div class="panel-body text-center">
					<!-- ここからフォーム -->
					<%= form_for @game do |f| %>

						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<%= f.label :title,  "タイトル"%>
						        	<%= f.text_field :title ,:class => 'form-control',:placeholder => "タイトル	", autofocus: true ,required: 'true'%>
								</div>
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<%= f.label :place,  "場所"%>
						        	<%= f.text_field :place ,:class => 'form-control', autofocus: true ,required: 'true'%>
								</div>
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col-sm-6">
								<%= f.submit "登録", class: "btn btn-danger btn-block btn-lg" %>
							</div>
							<div class="col-sm-6">
								<%= link_to "戻る" ,root_path, class: "btn btn-secondary btn-block btn-lg" %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>


<hr>
t.string "title"
t.text "description"<br>
t.datetime "datetime"<br>
t.string "place"<br>
t.string "level"<br>
t.string "price"<br>
t.text "remark"<br>
t.integer "team_id"<br>
t.string "active"<br>
t.string "closer_station"<br>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/schedules/index.html.erb
<h1>Schedules#index</h1>
<p>Find me in app/views/schedules/index.html.erb</p>


<%# @schedules.each do |schedules| %>
	<%# schedules.each do |schedule| %>
	<%#= schedule[0] %><!-- タイトル -->
	<%##= schedule[1] %><!-- 場所 -->
	<%#= schedule[2] %><!-- チーム名 -->
	<%# end %>
<%# end %>

<div class="app-menu">
	<h2>スケジュール</h2>
</div>
<div class="ticket-box btn-toolbar">
	<div class="ticket-box-date">
		xx/xx(土)
	</div>
	<div class="ticket-box-date-detail">
		>詳細はこちら
	</div>
	<div class="ticket-box-detail">
		<p>・集合場所：</p>
		<p>・集合時間：</p>
		<p>・対戦相手：</p>
		<p>・連絡事項：</p>
	</div>
	<div class="ticket-box-attendance btn-grou">
		<button class="btn btn-danger ticket-box-attendance-item">参加</button>
		<button class="btn btn-info ticket-box-attendance-item">欠席</button>
		<button class="btn btn-secondary ticket-box-attendance-item">保留</button>
	</div>
</div>



<%= link_to "new schedule", new_schedule_path %>



<style type="text/css" media="screen">
	.app-menu{
		margin: 0 auto;
		text-align: center;
		width: 90%;
		border-bottom: 0.5px solid gray;
		margin-bottom: 10px;
	}

	.app-team-manage{
	    display: table;
   		width: 95%;
		margin: 0 auto;
		border-radius: 5px;
		border: 0.5px solid gray;
		box-shadow: 5px 10px 20px rgba(0,0,0,0.25);
	}

	.app-team-top{

	}

	.app-team-top-image{
		width: 40%;
		height: 120px;
		float: left;
		/*background-color: red;*/
		/*padding: 10px;*/
		border: 1px solid red;

	}

	.app-team-top-name{
		width: 60%;
		height: 120px;
		float: right;
		/*background-color: yellow;*/
	}



	.app-team-comman-nav {
	    display: table;
	    margin: 0 auto;
	    width: 98%;
	    background: #FFF;
	    /*background-color: pink;*/
	}

	.app-team-comman-nav-item {
	    display: table-cell;
	    text-align: center;
	    vertical-align: middle;
	    /*background-color: hotpink;*/
	    width: 30%;
	}

	.app-team-title{
		width: 100%;
		height: 60px;
		/*background-color: red;*/
	}
	.app-team-command{
	    margin: 0 auto;
	    width: 98%;
		/*height: 40px;*/
		/*background-color: green;*/
	}

	.app-team-btn{
		width: 90%;
	}

	.app-team-show{
		width: 100%;
		height: 40px;
		/*background-color: yellow;*/
		padding-left: 30px;
	}

	.app-team-show-icon{
		padding-right: 30px;
		font-size: 20px;
		float: right;
	}
	
</style>

app/views/schedules/manage.html.erb
<h1>Schedules#manage</h1>
<p>Find me in app/views/schedules/manage.html.erb</p>


<ul>
	<% @teamusers.each do |team| %>
		<li>
			<%= team.id %>|
			<%= link_to 'add', new_schedule_path(team_id: team.id) %>

		</li>

	<% end %>
</ul>

app/views/schedules/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="text-center">
						<span style="font-size:24px;">スケジュール登録</span>
					</div>
					<hr>
				</div>

				<div class="container">
					<div class="panel-body text-center">
						<br>
						<!-- ここからフォーム -->
						<%= form_for @schedule do |f| %>
							<% if  @admin_team_flag %>
								<div class="row">
									<div class="col-md-12 select">
										<div class="form-group">
											<%= f.label :チーム %>
											<%= f.select :team_id, @admin_teams.map{|t| [t.team.name, t.id]} , {prompt:"チームを選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
										</div>
									</div>
								</div>
								<br>
							<% else %>

							<% end %>
							<div class="row">
								<div class="col-md-12 select">
									<div class="form-group">
										<%= f.label :name,  "タイトル"%>
							        	<%= f.text_field :name ,:class => 'form-control',:placeholder => "チームとの練習試合、等", autofocus: true ,required: 'true'%>
									</div>
								</div>
							</div>
							<br>
							<div class="row">
								<div class="col-md-12 select">
									<div class="form-group">
										<%= f.label :place,  "場所"%>
							        	<%= f.text_field :place ,:class => 'form-control',:placeholder => "未定の場合は、未入力可。", autofocus: true%>
									</div>
								</div>
							</div>

							<br>
							<hr>
							<br>
							<div class="row">
								<div class="col-md-12 select">
									<div class="form-group">
										<%= f.label :datetime,  "開始時間"%><br>
							        	<%= f.datetime_select :datetime ,:class => 'form-control'%>
									</div>
								</div>
							</div>
							<br>
							<div class="row">
								<div class="col-md-12 select">
									<div class="form-group">
										<%= f.label :datetime,  "終了時間"%><br>
							        	<%= f.datetime_select :datetime ,:class => 'form-control'%>
									</div>
								</div>
							</div>

							<br>
							<hr>
							<br>
							<div class="row">
								<div class="col-md-12 select">
									<div class="form-group">
										<%= f.label :remark,  "連絡事項"%>
							        	<%= f.text_area :remark ,:class => 'form-control',:placeholder => "連絡事項等を入力してください", autofocus: true ,required: 'true' %>
									</div>
								</div>
							</div>
							<br>

							<div class="row">
								<div class="col-6">
									<%= f.submit "登録", class: "btn btn-danger btn-block btn-lg" %>
								</div>
								<div class="col-6">
									<%= link_to "戻る" ,root_path, class: "btn btn-secondary btn-block btn-lg" %>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render 'partial/footer' %>

app/views/team_users/apply.html.erb
<div class="container">
	<div class="panel panel-default">
	<div class="panel-heading">
		チームを検索（チームキーを入力してください）
	    <div class="pull-right">
	        <div class="btn-group">
				<%= form_tag apply_to_team_path, :method => 'get' do %>
				<%#　projects_pathはモデル名で読みかえること %>
				  <p>
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
				  </p>
				<% end %>
	        </div>
	    </div>

	</div>
	<% if @teams.presence %>
	<% @teams.each do |team| %>
		<div class="col-6"><%= team.name %></div>
		<div class="col-6">
			<%#= link_to 'apply', controller: 'team_users', action: 'create', team_id: team.id, status: 0 %>
			<%= link_to 'apply', team_users_path(team_id: team.id, status: 0), method: :post %>

			</div>
	<% end %>
	<% end %>
</div>

<%= render 'partial/footer' %>

app/views/team_users/index.html.erb
<h1>TeamUsers#index</h1>



<h2>管理チーム一覧</h2>
<div class="container">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <% @team_users.each do |team_users| %>
      <tr>
          <td><%= team_users.team.name %></td>
          <td><%= team_users.team.name %></td>
          <td><%= link_to '招待', controller: 'team_users', action: 'new',
                    team_id: team_users.id, invited_id: current_user.id %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <div class="ticket-box-attendance btn-grou">
    <button class="btn btn-primary ticket-box-attendance-item">招待</button>
    <button class="btn btn-secondary ticket-box-attendance-item">編集</button>
  </div>



</div>



<style type="text/css" media="screen">

  .ticket-box-attendance{
    padding-top: 5px;
    width: 100%;
    height: 50px;
    /*background-color: yellow;*/


    display: table;
    table-layout: fixed;
    text-align: center;
    width: 100%;

  }


  .ticket-box-attendance-item{
    display: table-cell;
    vertical-align: middle;
    width: 30%;
    margin-left: 8px;
  }
</style>

app/views/team_users/invite.html.erb
invite.html.erb
<div class="container">
	<div class="panel panel-default">
	<div class="panel-heading">
		チームを検索（チームキーを入力してください）
	    
	    <div class="pull-right">
	        <div class="btn-group">
				<%= form_tag invite_to_team_path, :method => 'get' do %> 
				  <p>
				    <%= text_field_tag :search, params[:search] %>
				    <%= submit_tag "Search", :name => nil %>
				  </p>
				<% end %>

				<%# @users.each do |user| %>
					<%#= user.id %>
				<%# end %>
	        </div>
	    </div>

	</div>
	<%# if @teams.presence %>
	<%# @teams.each do |team| %>
		<div class="col-6"><%#= team.name %></div>
		<div class="col-6">
			<%#= link_to 'apply', controller: 'team_users', action: 'create', team_id: team.id, status: 0 %>
			<%#= link_to 'apply', team_users_path(team_id: team.id, status: 0), method: :post %>

			</div>
	<%# end %>
	<%# end %>
</div>

<%= render 'partial/footer' %>

app/views/team_users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="text-center">
						<span style="font-size:24px;">チームに招待</span>
					</div>
				</div>
				<div class="panel-body">
					<!-- ここからフォーム -->
					<%= form_for @team_user do |f| %>
						<div class="row">
							<div class="col-md-12 select">
								<div class="form-group">
									<%= hidden_field_tag :team_id, @team_id %>
						        	<%= f.text_field :remark, :class => 'form-control',:placeholder => "招待したいユーザーのメールアドレスまたはユーザー名を入力", autofocus: true ,required: 'true' %>
								</div>
							</div>
						</div>
						<div class="actions">
							<%= f.submit "Save", class: "btn btn-danger" %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
show.html.erb