config/routes.rb
Rails.application.routes.draw do
  root :to => "apps#index"

  get '/apps/about' => 'apps#about', as: 'app_about'

  get '/apps/message' => 'apps#message', as: 'app_message'
  get '/apps/team' => 'apps#team', as: 'app_team'
  get '/apps/schedule' => 'apps#schedule', as: 'app_schedule'
  get '/apps/game' => 'apps#game', as: 'app_game'
  get '/apps/profile' => 'apps#profile', as: 'app_profile'

  get '/schedules/manage' => 'schedules#manage', as: 'schedules_manage'
  get '/team/manage/:id' => 'teams#manage', as: 'team_manage'

  get 'team/apply2team' => 'team_users#apply', as: 'apply_to_team'
  get 'team/invite2team' => 'team_users#invite', as: 'invite_to_team'

  # resources :users, only: [:show]
  resources :apps
  resources :teams
  resources :schedules
  resources :team_users
  resources :games

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team

	geocoded_by :place
	after_validation :geocode, :if => :place_changed?
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :team


	geocoded_by :place

end

app/models/schedule_user.rb
class ScheduleUser < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :team_users
	has_many :users, through: :team_users

	has_many :schedules
	attachment :image
	#mount_uploader :picture, PictureUploader
	geocoded_by :active_place
	after_validation :geocode, :if => :active_place_changed?

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Team.where(['team_key LIKE ?', "%#{search}%"])
      # Team.where(:team_key, "%#{search}%"])
    # else
	 # Team.all #全て表示。
    end
  end
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :team_users
	has_many :teams, through: :team_users
	accepts_nested_attributes_for :team_users


  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      User.where(['id LIKE ?', "%#{search}%"])
    else
      User.all #全て表示。
    end
  end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	def index
		# いずれかのチームの管理者か否か判定
		if user_signed_in?
			@admin = 0

			@admin = TeamUser.where("(user_id = ?) AND (admin = ?)", current_user.id,1)
			if @admin.presence
				@admin = true
			else
				@admin = false
			end

			@schedules = []
		 	teams = TeamUser.where(user_id: current_user.id).pluck(:team_id).uniq
			teams.each { |team|
	        schedule = nil
			  	# debugger
			  	schedule = []
			  	schedule << Team.where(id: team).pluck(:name)[0] # team name
			  	schedule << Schedule.where(team_id: team).pluck(:team_id, :name, :place)
				#参加人数
			  	#欠席人数
			  	#保留人数
			  	#debugger

	        @schedules << schedule
			# debugger
			}
		end
	end

	def message
	end
	
	def team
	end

	def schduele
	end

	def profile
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  	@game = Game.new
  end

  def create
  	@game = Game.new(game_params)
  	@game.team_id = 1
  	# debugger
  	@game.save
  	redirect_to new_game_path
  end


  private
    def game_params
    	params.require(:game).permit(:title, :place)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def manage
    @teamusers = TeamUser.where(user_id: current_user.id)
    # debugger

    @teams = []
    teams = TeamUser.where(user_id: current_user.id).pluck(:team_id).uniq
    teams.each { |team|
        schedule = nil
        schedule = Schedule.where(team_id: team).pluck(:name, :place, team.name)
        @schedules << schedule
    }

  end

  def new
  	@schedule = Schedule.new
    @admin_teams = TeamUser.where(user_id: current_user, admin: true)
    @admin_teams.count
    if @admin_teams.count >= 2
      @admin_team_flag = true
    else
      @admin_team_flag = false
    end
  end

  def create
  	@schedule = Schedule.new(schedule_params)
  	# @schedule.team_id = params[:team_id]

  	@schedule.save
    # debugger
  	redirect_to root_path
  end

  def index
		@schedules = []
	 	teams = TeamUser.where(user_id: current_user.id).pluck(:team_id).uniq
		teams.each { |team|
        schedule = nil
		  	schedule = Schedule.where(team_id: team).pluck(:name, :place, team.name)
        @schedules << schedule
		}
  end

  private
    def schedule_params
    	params.require(:schedule).permit(:name, :place, :team_id, :datetime, :remark)
    end
end

app/controllers/team_users_controller.rb
class TeamUsersController < ApplicationController
  def index
    # debugger
  	@team_users = TeamUser.where(user_id: current_user.id, admin: true)
  end
  
  def new
  	@team_user = TeamUser.new
    @team_id = params[:team_id]
    status = params[:status]
    # debugger
  end

  def create
    @team = TeamUser.new
    @team.team_id = params[:team_id]
    @team.user_id = current_user.id
    @team.admin = 0
    @team.status = params[:status]
    @team.save
    redirect_to root_path
  end

  def apply
    @teams = Team.search(params[:search])
  end

  def invite
      @teams = Team.search(params[:search])
  end

  private
  def team_params
  	params.require(:team_user).permit(:team_id, :user_id, :remark)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index

    @teams = current_user.teams.pluck(:id, :name, :image_id)
    @teams_info = []
    @teams.each{|team|
      team << TeamUser.where(team_id: team[0]).count
      @teams_info << team
    }

    @teams = Team.all
  end

  def invite
    @team_id = params[:team_id]
    debugger

    @users = User.search(params[:search])
    debugger
  end

  def join_new
  end

  def show
    @team = Team.find(params[:id])
    @team_menber = TeamUser.where(team_id: params[:id])

    @users = User.search(params[:search])
  end

  def new
  	@team = current_user.teams.build
  end

  def create
  	@team = current_user.teams.build(team_params)
    @team.active = true
    @team.team_key = SecureRandom.hex(5)

  	if @team.save
	  	@team_user = TeamUser.new
	  	@team_user.team_id = @team.id
	  	@team_user.user_id = current_user.id
	  	@team_user.status = 2
	  	@team_user.admin = 1
	  	if !(@team_user.save)
	  		@team.destroy
	  		redirect_to new_team_path , notice: "チームを作成できませんでした。"
	  	end
      # debugger
  		redirect_to team_path(@team), notice: "チームを作成しました。"
  	else
        redirect_to new_team_path , notice: "チームを作成できませんでした。"
  	end
  end

  def edit
    @team = Team.find(params[:id])

  end

  def update
    team = Team.find(params[:id])
    team.update(team_params)
    redirect_to team_path(team.id)

  end


  def manage
    
  end


  private
  def team_params
  	params.require(:team).permit(:name, :organization, :level, :active_place,:description, :team_key, :active, :image, :picture, :admin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #ViewのFormで取得したパラメータをモデルに渡す
    # @users = User.search(params[:search])
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/team_user_helper.rb
module TeamUserHelper
end

app/helpers/team_users_helper.rb
module TeamUsersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/apps/about.html.erb
<%= render 'partial/navbar' %>


<div class="container">
	<div class="about-text"><h1>Wanakaの使い方</h1></div>
	<div class="row"></div>


</div>



<div class="row">
  <div class="col-lg-4 explain">
    <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
    <h2>Apply！</h2>
    <p>一般ユーザーは、チームキーワードを入力し、承認依頼するをします。</p>
  </div><!-- /.col-lg-4 -->
  <div class="col-lg-4 explain">
    <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
    <h2>Approve！</h2>
    <p>チーム管理者は、受領した依頼を確認し、承認します。</p>
  </div><!-- /.col-lg-4 -->
  <div class="col-lg-4 explain">
    <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
    <h2>Join！</h2>
    <p>おめでとうございます！チームにJoin出来ました！</p>

  </div><!-- /.col-lg-4 -->
</div><!-- /.row -->


<%= render 'partial/footer' %>

<style type="text/css" media="screen">
	body{
		padding-top: 70px;
	}

	.about-text{
		text-align: center;
	}


	.explain{
		text-align: center;
		margin: 0 auto;
	}
</style>

app/views/apps/game.html.erb
game.html.erb

app/views/apps/index.html.erb
<% if  user_signed_in? %>
	<% if @admin %>
		<!-- サインインしている && 所属しているいずれかのグループで管理者-->
		<%= render 'partial/view_for_admin' %>
		<%= render 'partial/adminnavbar' %>
	<% else %>
		<!-- サインインしている && 所属しているいずれかのグループで管理者出ない-->
		<br><br>
		<%= render 'partial/navbar' %>
		<%= render 'partial/view_for_signed' %>
		<%#= render 'partial/footer' %>
	<% end %>
<% else %>
	<!-- サインインしていない　-->
	<%= render 'partial/view_for_unsigned' %>

<% end %>
<%= render 'partial/footer' %>



<style type="text/css" media="screen">

	.jumbotron {
	    padding-top: 0px;
	    background: linear-gradient( rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.6) ), url(images/boys-2769553_1920.jpg);
    	/*background-image: url(/images/person-845325_1920.jpg);*/
		background-size: cover;
		background-position: 50% 50%;
		height: 320px;
		color: white;
		margin-top: 56px;
	}



</style>

app/views/apps/message.html.erb
message.html.erb


<%= render 'partial/adminnavbar' %>

app/views/apps/profile.html.erb
profile.html.erb

app/views/apps/schedule.html.erb
<%# @schedules.each do |schedules| %>
	<%# schedules.each do |schedule| %>
	<%#= schedule[0] %><!-- タイトル -->
	<%##= schedule[1] %><!-- 場所 -->
	<%#= schedule[2] %><!-- チーム名 -->
	<%# end %>
<%# end %>

<div class="app-menu">
	<h2>スケジュール</h2>
</div>
<div class="ticket-box btn-toolbar">
	<div class="ticket-box-date">
		xx/xx(土)
	</div>
	<div class="ticket-box-date-detail">
		>詳細はこちら
	</div>
	<div class="ticket-box-detail">
		<p>・場所：</p>
		<p>・内容：</p>
		<p>・連絡事項：</p>
	</div>
	<div class="ticket-box-attendance btn-grou">
		<button class="btn btn-danger ticket-box-attendance-item">参加</button>
		<button class="btn btn-info ticket-box-attendance-item">欠席</button>
		<button class="btn btn-secondary ticket-box-attendance-item">保留</button>
	</div>
</div>

<%= link_to(new_schedule_path, class: 'footer-item') do %>
	<div class="add-btn">+</div>
<% end %>


<%= link_to "new schedule", new_schedule_path %>
<%= render 'partial/adminnavbar'%>

<style type="text/css" media="screen">

	.app-menu{
		margin: 0 auto;
		text-align: center;
		width: 90%;
		border-bottom: 0.5px solid gray;
		margin-bottom: 10px;
	}

	.app-team-manage{
	    display: table;
   		width: 95%;
		margin: 0 auto;
		border-radius: 5px;
		border: 0.5px solid gray;
		box-shadow: 5px 10px 20px rgba(0,0,0,0.25);
	}

	.ticket-box{
		width: 90%;
		/*height: 200px;*/
		box-shadow: 5px 10px 20px rgba(0,0,0,0.25);
		margin: 24px auto;
		border-left: 60px solid #1abc9c;
	}

	.ticket-box-date{
		width: 70%;
		height: 30px;
		padding-top: 3px;
		padding-left: 10px;
	}

	.ticket-box-detail{
		width: 100%;
		padding-top: 10px;
		padding-left: 40px;
		font-size: 14px;
		line-height: 10px;
	}

	.ticket-box-date-detail{
		width: 20%;
		float: right;
		margin: auto auto;
		font-size: 10px;
	}

	.ticket-box-attendance{
		padding: 5px 0;
		width: 100%;
		/*height: 50px;*/
		display: table;
		table-layout: fixed;
		text-align: center;
		width: 100%;
	}

	.ticket-box-attendance-item{
		display: table-cell;
		vertical-align: middle;
		width: 30%;
		margin-left: 8px;
	}

	.add-btn{
		width: 70px;
		height: 70px;
		border-radius: 50%;
		text-align: center;

		overflow: hidden;
		position: fixed;
		bottom: 80px;
		right: 10px;
		font-size: 60px;

		background-color: #26a69b;
		color: #CFD8DC;
		border: none;
		box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
		transition: all 0.3s ease 0s;
		/*outline: none;*/

		display: flex;
		align-items: center;
		justify-content: center;
	}

	.add-btn:hover{
		background-color: #2EE59D;
		box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);
		color: #fff;
		transform: translateY(-7px);
	}

</style>

app/views/apps/team.html.erb
team.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wanaka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>

    <%= link_to 'top', root_path %>

    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
          toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>

    <% end %>
    <!-- <script>$( "#alarm" ).timeDropper();</script> -->
  </body>
</html>

app/views/partial/_adminnavbar.html.erb
<div class="footer">
	<%= link_to(app_schedule_path, class: 'footer-item') do %>
	    <div class="footer-item-icon">
	    	<i class="far fa-calendar-alt"></i>
	    </div>
	    <div class="footer-item-text">Schedule</div>
	<% end %>
	<%= link_to(app_game_path, class: 'footer-item', data:{no_turbolink: true}) do %>
	    <div class="footer-item-icon">
	    	<i class="far fa-futbol"></i>
	    </div>
	    <div class="footer-item-text">Game</div>
	<% end %>
	<%= link_to(teams_path, class: 'footer-item') do %>
	    <div class="footer-item-icon">
	    	<i class="fas fa-users"></i>
	    </div>
	    <div class="footer-item-text">Team</div>
	<% end %>
	<%= link_to(app_message_path, class: 'footer-item', data:{no_turbolink: true}) do %>
	    <div class="footer-item-icon">
	    	<i class="far fa-comment-alt"></i>
	    </div>
	    <div class="footer-item-text">Message</div>
	<% end %>

	<%= link_to(app_profile_path, class: 'footer-item') do %>
	    <div class="footer-item-icon">
	    	<i class="far fa-address-card"></i>
	    </div>
	    <div class="footer-item-text">Menu</div>
	<% end %>

</div>

<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>

app/views/partial/_footer.html.erb
<footer>
	@ copy right all reserve by st
</footer>

<% if (user_signed_in?) %>
　ログイン中：UserID ＝＞　<%= current_user.id %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
	未ログイン
<% end %>




<br>
<br>
<br>
<style type="text/css" media="screen">
	footer{
		height: 40px;
		padding-top: 10px;
		margin-top: 30px;
		width: 100%;
		background: #607D8B;
		text-align: center;
		font-size: 10.5px;
		color: #E0E0E0;
	}
</style>

app/views/partial/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top navbar-color">
    <a class="navbar-brand" href="#">Wanaka</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
      </ul>
      <div class="form-inline mt-2 mt-md-0 nav-item">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">新規登録</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">チーム作成</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Wanakaとは</a>
            </li>
          </ul>
      </div>
    </div>
  </nav>
</header>


<style type="text/css" media="screen">
  .navbar-color{
   background-color: #EC715F;
  }


</style>

app/views/partial/_sitemap.html.erb
<hr>
<ul>
	<li>ユーザー管理</li>
	<li><%= link_to 'log in', new_user_session_path %></li>
	<li><%= link_to 'sign in', new_user_registration_path %></li>
	<% if user_signed_in? %>

	<% end %>
</ul>
<ul>
	<li>チーム</li>
	<li><%= link_to 'index', teams_path %></li>
	<li><%= link_to 'new', new_team_path %></li>
	<li><%#= link_to 'join from_leader', offer_to_join_path %></li>
	<li><%#= link_to 'join from_member', apply_to_team_path %></li>

</ul>
<ul>
	<li>スケジュール</li>
	<li><%= link_to 'manage', schedules_manage_path %></li>

</ul>
<hr>
<ul>
	<li>ゲームマッチング</li>
	<li><%= link_to 'index' %></li>
	<li><%= link_to 'new', new_game_path %></li>
</ul>

app/views/partial/_view_for_admin.html.erb
_view_for_.html.erb



<div class="app-menu">
	<h2>チーム管理</h2>
</div>

<div class="app-team-manage">
	<div class="app-team-top">
		<div class="app-team-top-image">
		</div>

		<div class="app-team-top-name">

		</div>
	</div>
	<hr>

	<div class="app-team-command">
		<div class="app-team-comman-nav">
		    <div class="app-team-comman-nav-item"><button class="btn btn-danger app-team-btn">予定作成</button></div>
		    <div class="app-team-comman-nav-item"><button class="btn btn-success app-team-btn">メンバー招待</button></div>
		    <div class="app-team-comman-nav-item"><button class="btn btn-secondary app-team-btn">メンバー管理</button></div>
		</div>
	</div>
	<hr>
	<div class="app-team-show">
		チームの詳細を表示する
		<div class="app-team-show-icon">
			<i class="fas fa-angle-right"></i>
		</div>
	</div>
</div>
<div class="team-add">
	<div class="team-add-icon">
		+ <span style="font-size: 11px;">別のチームを作成する</span>
	</div>
	<div class="team-add-text">
	</div>
</div>

<br>
<hr>
<div class="app-menu">
	<h2>スケジュール</h2>
</div>

<div class="ticket-box btn-toolbar">
	<div class="ticket-box-date">
		xx/xx(土)
	</div>
	<div class="ticket-box-date-detail">
		>詳細はこちら
	</div>
	<div class="ticket-box-detail">
		<p>・集合場所：</p>
		<p>・集合時間：</p>
		<p>・対戦相手：</p>
		<p>・連絡事項：</p>
	</div>
	<div class="ticket-box-attendance btn-grou">
		<button class="btn btn-danger ticket-box-attendance-item">参加</button>
		<button class="btn btn-info ticket-box-attendance-item">欠席</button>
		<button class="btn btn-secondary ticket-box-attendance-item">保留</button>
	</div>
</div>

<div class="ticket-box btn-toolbar">
	<div class="ticket-box-date">
		xx/xx(土)
	</div>
	<div class="ticket-box-date-detail">
		>詳細はこちら
	</div>
	<div class="ticket-box-detail">
		<p>・集合場所：</p>
		<p>・集合時間：</p>
		<p>・対戦相手：</p>
		<p>・連絡事項：</p>
	</div>
	<div class="ticket-box-attendance btn-grou">
		<button class="btn btn-danger ticket-box-attendance-item">参加</button>
		<button class="btn btn-info ticket-box-attendance-item">欠席</button>
		<button class="btn btn-secondary ticket-box-attendance-item">保留</button>
	</div>
</div>

<br>
<hr>
<div class="app-menu">
	<h2>マッチメイク</h2>
</div>

<div class="container">
	<div class="row">
		
		<div class="col-lg-2 col-md-4 col-sm-6 app-game-box">
			<div class="app-game-image">
			</div>
			<div class="app-game-info">
				<div class="app-game-info-title">
				</div>
				<div class="app-game-info-detail">
				</div>
			</div>
		</div>
		<div class="col-lg-2 col-md-4 col-sm-6 app-game-box">
			<div class="app-game-image">
			</div>
			<div class="app-game-info">
				<div class="app-game-info-title">
				</div>
				<div class="app-game-info-detail">
				</div>
			</div>
		</div>
		<div class="col-lg-2 col-md-4 col-sm-6 app-game-box">
			<div class="app-game-image">
			</div>
			<div class="app-game-info">
				<div class="app-game-info-title">
				</div>
				<div class="app-game-info-detail">
				</div>
			</div>
		</div>
		<div class="col-lg-2 col-md-4 col-sm-6 app-game-box">
			<div class="app-game-image">
			</div>
			<div class="app-game-info">
				<div class="app-game-info-title">
				</div>
				<div class="app-game-info-detail">
				</div>
			</div>
		</div>
		<div class="col-lg-2 col-md-4 col-sm-6 app-game-box">
			<div class="app-game-image">
			</div>
			<div class="app-game-info">
				<div class="app-game-info-title">
				</div>
				<div class="app-game-info-detail">
				</div>
			</div>
		</div>
		<div class="col-lg-2 col-md-4 col-sm-6 app-game-box">
			<div class="app-game-image">
			</div>
			<div class="app-game-info">
				<div class="app-game-info-title">
				</div>
				<div class="app-game-info-detail">
				</div>
			</div>
		</div>
	</div>

</div>



<div class="match-make">

	<button type="button" class="btn btn-primary btn-lg match-make-btn">対戦相手</button>
	<button type="button" class="btn btn-secondary btn-lg match-make-btn">ゲームを申込</button>
</div>
<br><br>

app/views/partial/_view_for_signed.html.erb
  <div class="col-lg-4" style="text-align: center; font-size: 12px; padding: 0 40px;">
    <h2 style="font-size: 24px; margin: 20px 20px">XXX</h2>
		<%= link_to(apply_to_team_path) do %>
	    	<button class="btn btn-primary" style="width: 240px;">既にあるチームに参加</button>
		<% end %>
    <br>
  </div><!-- /.col-lg-4 -->
  <div class="col-lg-4" style="text-align: center; font-size: 12px; padding: 0 40px;">
    <h2 style="font-size: 24px; margin: 20px 20px">XXX</h2>
		<%= link_to(new_team_path) do %>
    		<button class="btn btn-info" style="width: 240px;">新たにチームを作成</button>
		<% end %>
    <br>
  </div><!-- /.col-lg-4 -->
  <div class="col-lg-4" style="text-align: center; font-size: 12px; padding: 0 40px;">
    <h2 style="font-size: 24px; margin: 20px 20px;">XXX</h2>
		<%= link_to(new_user_registration_path) do %>
	    	<button class="btn btn-danger" style="width: 240px;">使い方を見る</button>
		<% end %>
    <br>
  </div><!-- /.col-lg-4 -->
</div><!-- /.row -->

app/views/partial/_view_for_unsigned.html.erb
	<div class="jumbotron">
		<%= render 'partial/navbar' %>
	  <div class="container">
	   <div class="row">
	     <div class="col-md-6 col-md-offset-3 text-center">
	       <h1 class="display-3">Hello, world!</h1>
	     </div>
	   </div>
	  </div>
	</div>

    <div class="row" style="background-color: #ECEFF1; height: 300px;">
		<div class="col-12 top-menu">What's Wanaka?</div>
		<!-- <div class="col-12 top-menu-border"></div> -->

      <div class="col-md-6 offset-md-3" style="text-align: center; font-size: 12px; padding: 0 40px;">
      	<p style="font-size: 16px;">Wanakaとは、チームを管理するための新しいサービスです。<br></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->

     <!-- Three columns of text below the carousel -->
     <br>
     <br>
    <div class="row">
		<div class="col-12 top-menu">Feature</div>
		<br>
		<br>
		<br>
		<br>
		<!-- <div class="col-12 top-menu-border"></div> -->

      <div class="col-lg-4" style="text-align: center; font-size: 12px; padding: 0 40px;">
        <img class="rounded" src="images/hierarchical-structure.png" alt="" width="140" height="140">
        <h2 style="font-size: 24px; margin: 20px 20px">チーム管理</h2>
        <p>XXX</p>
        <br>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4" style="text-align: center; font-size: 12px; padding: 0 40px;">
        <img class="rounded" src="images/clipboard.png" alt="" width="140" height="140">
        <h2 style="font-size: 24px; margin: 20px 20px">出席管理</h2>
        <p>XXX</p>
        <br>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4" style="text-align: center; font-size: 12px; padding: 0 40px;">
        <img class="rounded-circle" src="images/deal.png" alt="" width="140" height="140">

        <h2 style="font-size: 24px; margin: 20px 20px;">MatchMaking</h2>
        <p>XXX</p>
        <br>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->



    <div class="row" style="background-color: #ECEFF1; height: 300px;">
		<div class="col-12 top-menu">Join?</div>
		<!-- <div class="col-12 top-menu-border"></div> -->
		<br>

		<%= link_to(new_user_registration_path) do %>
			<div class="col-md-6 offset-md-3" style="text-align: center; font-size: 12px; padding: 0 40px;">
				<button class="btn btn-info" style="width: 200px; height: 60px;">会員登録</button>
			</div>
		<% end %>
		<%= link_to(new_user_session_path) do %>
			<div class="col-md-6 offset-md-3" style="text-align: center; font-size: 12px; padding: 0 40px;">
				<button class="btn btn-primary" style="width: 200px; height: 60px;">ログイン</button>
			</div><!-- /.col-lg-4 -->
		<% end %>
	</div><!-- /.row -->